In [1]:
import pandas as pd

df_2013 = pd.read_csv('data\Hoteles\Hoteles_2013.csv')
df_2014 = pd.read_csv('data\Hoteles\Hoteles_2014.csv')
df_2015 = pd.read_csv('data\Hoteles\Hoteles_2015.csv')
df_2016 = pd.read_csv('data\Hoteles\Hoteles_2016.csv')
df_2017 = pd.read_csv('data\Hoteles\Hoteles_2017.csv')
df_2018 = pd.read_csv('data\Hoteles\Hoteles_2018.csv')
df_2019 = pd.read_csv('data\Hoteles\Hoteles_2019.csv')
df_2020 = pd.read_csv('data\Hoteles\Hoteles_2020.csv')

<>:3: SyntaxWarning: invalid escape sequence '\H'
<>:4: SyntaxWarning: invalid escape sequence '\H'
<>:5: SyntaxWarning: invalid escape sequence '\H'
<>:6: SyntaxWarning: invalid escape sequence '\H'
<>:7: SyntaxWarning: invalid escape sequence '\H'
<>:8: SyntaxWarning: invalid escape sequence '\H'
<>:9: SyntaxWarning: invalid escape sequence '\H'
<>:10: SyntaxWarning: invalid escape sequence '\H'
<>:3: SyntaxWarning: invalid escape sequence '\H'
<>:4: SyntaxWarning: invalid escape sequence '\H'
<>:5: SyntaxWarning: invalid escape sequence '\H'
<>:6: SyntaxWarning: invalid escape sequence '\H'
<>:7: SyntaxWarning: invalid escape sequence '\H'
<>:8: SyntaxWarning: invalid escape sequence '\H'
<>:9: SyntaxWarning: invalid escape sequence '\H'
<>:10: SyntaxWarning: invalid escape sequence '\H'
C:\Users\fofoy\AppData\Local\Temp\ipykernel_8016\3779001808.py:3: SyntaxWarning: invalid escape sequence '\H'
  df_2013 = pd.read_csv('data\Hoteles\Hoteles_2013.csv')
C:\Users\fofoy\AppData\Local\Temp\ipykernel_8016\3779001808.py:4: SyntaxWarning: invalid escape sequence '\H'
  df_2014 = pd.read_csv('data\Hoteles\Hoteles_2014.csv')
C:\Users\fofoy\AppData\Local\Temp\ipykernel_8016\3779001808.py:5: SyntaxWarning: invalid escape sequence '\H'
  df_2015 = pd.read_csv('data\Hoteles\Hoteles_2015.csv')
C:\Users\fofoy\AppData\Local\Temp\ipykernel_8016\3779001808.py:6: SyntaxWarning: invalid escape sequence '\H'
  df_2016 = pd.read_csv('data\Hoteles\Hoteles_2016.csv')
C:\Users\fofoy\AppData\Local\Temp\ipykernel_8016\3779001808.py:7: SyntaxWarning: invalid escape sequence '\H'
  df_2017 = pd.read_csv('data\Hoteles\Hoteles_2017.csv')
C:\Users\fofoy\AppData\Local\Temp\ipykernel_8016\3779001808.py:8: SyntaxWarning: invalid escape sequence '\H'
  df_2018 = pd.read_csv('data\Hoteles\Hoteles_2018.csv')
C:\Users\fofoy\AppData\Local\Temp\ipykernel_8016\3779001808.py:9: SyntaxWarning: invalid escape sequence '\H'
  df_2019 = pd.read_csv('data\Hoteles\Hoteles_2019.csv')
C:\Users\fofoy\AppData\Local\Temp\ipykernel_8016\3779001808.py:10: SyntaxWarning: invalid escape sequence '\H'
  df_2020 = pd.read_csv('data\Hoteles\Hoteles_2020.csv')

In [2]:
df = pd.concat([df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020])
df

,Unnamed: 0,municipio,total,5 estrellas,4 estrellas,3 estrellas,2 estrellas,1 estrellas,sin categoria,año
0,6,Estado,1647,106,204,273,148,230,685,2013
1,7,I Norte,28,0,2,2,1,8,15,2013
2,8,Bolaños,3,0,0,0,0,1,2,2013
3,9,Chimaltitán,1,0,0,0,0,0,1,2013
4,10,Colotlán,2,0,1,0,0,1,0,2013
...,...,...,...,...,...,...,...,...,...,...
114,120,ZAPOTILTIC,3,0,1,0,0,0,2,2020
115,121,ZAPOTITLAN DE VADILLO,1,0,0,0,0,0,1,2020
116,122,ZAPOTLAN DEL REY,2,1,0,1,0,0,0,2020
117,123,ZAPOTLAN EL GRANDE,15,0,2,7,3,3,0,2020
118,124,ZAPOTLANEJO,13,0,1,7,1,0,4,2020

In [3]:
df = df.drop(columns=["Unnamed: 0"])

In [4]:
df['municipio'] = df['municipio'].str.upper()

In [5]:
df = df[df['municipio'] != 'ESTADO']
df = df[df['municipio'] != 'I NORTE']
df = df[df['municipio'] != 'II ALTOS NORTE']
df = df[df['municipio'] != 'III ALTOS SUR']
df = df[df['municipio'] != 'IV CIÉNEGA']
df = df[df['municipio'] != 'V SURESTE']
df = df[df['municipio'] != 'VI SUR']
df = df[df['municipio'] != 'VII SIERRA DE AMULA']
df = df[df['municipio'] != 'VIII COSTA SUR']
df = df[df['municipio'] != 'IX COSTA NORTE']
df = df[df['municipio'] != 'X SIERRA OCCIDENTAL']
df = df[df['municipio'] != 'XI VALLES']
df = df[df['municipio'] != 'XII CENTRO']

In [6]:
df

,municipio,total,5 estrellas,4 estrellas,3 estrellas,2 estrellas,1 estrellas,sin categoria,año
2,BOLAÑOS,3,0,0,0,0,1,2,2013
3,CHIMALTITÁN,1,0,0,0,0,0,1,2013
4,COLOTLÁN,2,0,1,0,0,1,0,2013
5,HUEJÚCAR,4,0,0,0,0,4,0,2013
6,HUEJUQUILLA EL ALTO,4,0,0,2,0,0,2,2013
...,...,...,...,...,...,...,...,...,...
114,ZAPOTILTIC,3,0,1,0,0,0,2,2020
115,ZAPOTITLAN DE VADILLO,1,0,0,0,0,0,1,2020
116,ZAPOTLAN DEL REY,2,1,0,1,0,0,0,2020
117,ZAPOTLAN EL GRANDE,15,0,2,7,3,3,0,2020
118,ZAPOTLANEJO,13,0,1,7,1,0,4,2020

In [7]:
df.to_csv("data\Hoteles\Hoteles_Historico.csv", index=False)

<>:1: SyntaxWarning: invalid escape sequence '\H'
<>:1: SyntaxWarning: invalid escape sequence '\H'
C:\Users\fofoy\AppData\Local\Temp\ipykernel_8016\2968105972.py:1: SyntaxWarning: invalid escape sequence '\H'
  df.to_csv("data\Hoteles\Hoteles_Historico.csv", index=False)